[package]
name = "debug-project"
version = "0.1.0"
authors = ["Varkal <moreau.romain83@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
